// Pulls the two things the mobile client MUST NOT retype out of the web client.
//
//   dart run tool/sync_shared.dart
//
// 1. **i18n** — 547 keys x 2 locales. A second translation set drifts, and the
//    symptom is one sentence differing between two clients with nothing to report
//    it. The JSON is copied verbatim into `assets/i18n/`.
// 2. **theme tokens** — 4 themes x light/dark x 25 values live in `tokens.css`.
//    Hand-copying a palette is the same class of defect this repo has fixed eight
//    times, so they are generated.
//
// `test/shared_sync_test.dart` fails if what is committed no longer matches the
// web sources, which is what makes this a mechanism rather than a chore.
import 'dart:convert';
import 'dart:io';

final webRoot = Directory('../frontend-web');

void main() {
  if (!webRoot.existsSync()) {
    stderr.writeln('Run this from frontend-mobile/ — ../frontend-web must exist.');
    exit(1);
  }

  syncI18n();
  generateTokens();
}

// ---------------------------------------------------------------- i18n

/// The locale files the web client ships. Derived from the directory, not typed.
List<File> webLocaleFiles() =>
    Directory('${webRoot.path}/public/i18n')
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.json'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

void syncI18n() {
  final out = Directory('assets/i18n')..createSync(recursive: true);
  for (final src in webLocaleFiles()) {
    final name = src.uri.pathSegments.last;
    src.copySync('${out.path}/$name');
    stdout.writeln('i18n  <- $name');
  }
}

// ---------------------------------------------------------------- tokens

/// `[data-theme='name']` optionally followed by `.dark`, then a `{ ... }` block.
final _blockPattern = RegExp(
  r"\[data-theme='([a-z-]+)'\](\.dark)?\s*\{([^}]*)\}",
  multiLine: true,
);
final _declPattern = RegExp(r'--([a-z-]+)\s*:\s*([^;]+);');
final _varPattern = RegExp(r'var\(\s*--([a-z-]+)\s*\)');

/// Resolves `var(--x)` against the same block, then against the light fallback.
String _resolve(String value, Map<String, String> own, Map<String, String> fallback) {
  var out = value.trim();
  // A handful of nested references at most; the bound stops a cycle in bad data
  // from hanging the build instead of reporting.
  for (var depth = 0; depth < 8 && _varPattern.hasMatch(out); depth++) {
    out = out.replaceAllMapped(_varPattern, (m) {
      final key = m.group(1)!;
      return own[key] ?? fallback[key] ?? m.group(0)!;
    });
  }
  return out.trim();
}

/// theme -> mode -> token -> resolved value. Public so the test can re-derive it.
Map<String, Map<String, Map<String, String>>> parseTokens(String css) {
  final raw = <String, Map<String, Map<String, String>>>{};

  for (final block in _blockPattern.allMatches(css)) {
    final theme = block.group(1)!;
    final mode = block.group(2) == null ? 'light' : 'dark';
    final decls = <String, String>{};
    for (final decl in _declPattern.allMatches(block.group(3)!)) {
      decls[decl.group(1)!] = decl.group(2)!.trim();
    }
    (raw[theme] ??= {})[mode] = decls;
  }

  final resolved = <String, Map<String, Map<String, String>>>{};
  for (final entry in raw.entries) {
    final light = entry.value['light'] ?? const {};
    // Dark blocks only carry overrides; everything else cascades from light.
    // Merging here is what makes the generated dark map complete — reading only
    // the `.dark` block would silently drop most of the palette.
    final dark = {...light, ...?entry.value['dark']};

    resolved[entry.key] = {
      'light': {for (final k in light.keys) k: _resolve(light[k]!, light, light)},
      'dark': {for (final k in dark.keys) k: _resolve(dark[k]!, dark, light)},
    };
  }
  return resolved;
}

String renderTokens(Map<String, Map<String, Map<String, String>>> tokens) {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/sync_shared.dart from')
    ..writeln('// ../frontend-web/src/styles/tokens.css — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Values are kept as the strings CSS uses; `colorOf` parses the hex ones.')
    ..writeln('// Non-colour tokens (radii, shadows) stay strings on purpose rather than')
    ..writeln('// being classified here, because guessing wrong is silent.')
    ..writeln('library;')
    ..writeln()
    ..writeln('const Map<String, Map<String, Map<String, String>>> themeTokens = {');

  final themes = tokens.keys.toList()..sort();
  for (final theme in themes) {
    b.writeln("  '$theme': {");
    for (final mode in const ['light', 'dark']) {
      b.writeln("    '$mode': {");
      final keys = tokens[theme]![mode]!.keys.toList()..sort();
      for (final key in keys) {
        b.writeln("      '$key': '${tokens[theme]![mode]![key]}',");
      }
      b.writeln('    },');
    }
    b.writeln('  },');
  }
  b.writeln('};');
  return b.toString();
}

void generateTokens() {
  final css = File('${webRoot.path}/src/styles/tokens.css').readAsStringSync();
  final tokens = parseTokens(css);

  if (tokens.isEmpty) {
    stderr.writeln('Parsed zero themes out of tokens.css — refusing to write an empty file.');
    exit(1);
  }

  final out = File('lib/theme/tokens.g.dart')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(renderTokens(tokens));

  stdout.writeln(
    'tokens <- ${tokens.length} themes x 2 modes '
    'x ${tokens.values.first['light']!.length} values -> ${out.path}',
  );
}

/// Flattens a translation tree to dotted keys, so two locales can be compared.
Set<String> flattenKeys(Map<String, dynamic> tree, [String prefix = '']) {
  final keys = <String>{};
  for (final entry in tree.entries) {
    final path = prefix.isEmpty ? entry.key : '$prefix.${entry.key}';
    final value = entry.value;
    if (value is Map<String, dynamic>) {
      keys.addAll(flattenKeys(value, path));
    } else {
      keys.add(path);
    }
  }
  return keys;
}

Set<String> keysOfJson(String json) =>
    flattenKeys(jsonDecode(json) as Map<String, dynamic>);
