/**
 * Score-attack DTO shapes — mirror the backend's `ScoreRunDtos.cs`.
 *
 * Note what {@link SubmitScoreRunBody} does **not** have: score, lines, level,
 * duration. Those are server facts, and on the backend the command has no field
 * for them either — not "the handler remembers to ignore them", but *nowhere to
 * put them*. Adding them here would be the first step towards a client that
 * believes its own numbers are authoritative.
 */

/** Response to `POST /api/score-runs`. */
export interface ScoreRunStarted {
  readonly runId: string;
  readonly gameKey: string;
  /** Seed for the piece sequence — generated by the server, never chosen here. */
  readonly seed: number;
  readonly startedAt: string;
}

/** One placement: the final rotation, and the column of its leftmost cell. */
export interface ScorePlacement {
  readonly rotation: number;
  readonly column: number;
}

/** Request body for `POST /api/score-runs/{id}/submit`. */
export interface SubmitScoreRunBody {
  readonly placements: readonly ScorePlacement[];
}

/** Response to a submission — every number replayed by the server. */
export interface ScoreRunResult {
  readonly runId: string;
  readonly score: number;
  readonly lines: number;
  readonly level: number;
  readonly placements: number;
  readonly durationMs: number;
}

/** Score-leaderboard window. Matches the backend's `ScoreWindow` names. */
export type ScoreWindow = 'week' | 'month' | 'all';

/** The three windows, in the order the switcher shows them. */
export const SCORE_WINDOWS: readonly ScoreWindow[] = ['week', 'month', 'all'];

/** One row of the score leaderboard — a player's best run in the window. */
export interface ScoreLeaderboardEntry {
  readonly rank: number;
  readonly userId: string;
  readonly username: string;
  readonly score: number;
  readonly lines: number;
  readonly level: number;
  readonly finishedAt: string;
}
